# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

include:
- _include

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'House of Misfits'
description: 'Mental-Health Discord Server'
permalink: pretty
logo: "/assets/img/homlogo3.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Join
  url: /join/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Start Chatting
  url: /join

# Collections
collections:
  posts:
    title: Posts
    output: true
    feature_text: |
      # House of Misfits Blog
    feature_image: "https://picsum.photos/2560/600?image=866"
